name: PVPPlayer
author: MamayAdesu
api: 1.2.0
version: "1.0"
main: mamayadesu\pvpplayer\pvpplayer
website: https://github.com/mamayadesu/PocketMinePlugins/PVPlayer

commands:
 pvppon:
  permission: pvpplayer.on
  description: Turn on PVP for you.
  usage: /pvppon
 pvppoff:
  permission: pvpplayer.off
  description: Turn off PVP for you.
  usage: /pvppoff
 pvpp:
  permission: pvpplayer.check
  description: Check your PVP status.
  usage: /pvpp

permissions:
 pvpplayer.on:
  default: true
  description: Allows to turn on PVP.
 pvpplayer.off:
  default: true
  description: Allows to turn on PVP.
 pvpplayer.check:
  default: true
  description: Allows to check your PVP status
